# Generated by Django 3.1 on 2020-08-19 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200819_0938'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='addess',
            new_name='address',
        ),
    ]
