# Generated by Django 3.0.5 on 2020-07-29 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://www.soignon.fr/media/cache/big_filter/uploads/imports/pizza-au-chevre-poivrons-et-herbes-de-provence.jpg', max_length=500),
        ),
    ]
